my_yaml_i18n_routes:
    resource: "@AppCorredoresRiojaBundle/Resources/config/routing/routing_i18n.yml"
    type: be_simple_i18n
    prefix: /{_locale}

index:
    path:  /
    defaults:
        #_controller: AppCorredoresRiojaBundle:Default:index 
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /es/portada
        permanent: true
                